### PR TITLE
fix #1688

### PR DESCRIPTION
**Pull request by player0k**
fix issue: https://github.com/ThemeFuse/Unyson/issues/1688
it's need to test

### CODE REVIEW

**Comment by moldcraft** [comment]
1. Why this pull request has conflicts?
2. Can you please give the exact steps how to test this?

**Comment by player0k** [comment]
1. Add static page for posts
2. Select this page in settings screenshot
3. write title for posts page screen
3. Add breadcrumbs to template following extension install instructions
4.Go to posts page and check breadcrumbs title is the same as entered on step 3

**Comment by player0k** [comment]
The file which I changed has older version includes/class-breadcrumbs-builder.php than master

**Comment by moldcraft** [comment]
Please `git pull` and update the pull request with latest version, without conflicts

**Comment by player0k** [comment]
@moldcraft, conflict was resolved. Now you can merge it.

**Comment by moldcraft** [comment]
I saw. I added it in todo and will test later.

**Comment by moldcraft** [comment]
Thank you!

**Pull request merged**
